// Help Map file generated from application's resource.h file.  
  
// Commands (ID_* and IDM_*)  
#define HID_POPUP_SHOW_STATUS                   0x8005
#define HID_POPUP_TIME_CRITICAL                 0x8006
#define HID_POPUP_HIGHEST                       0x8007
#define HID_POPUP_ABOVE_NORMAL                  0x8008
#define HID_POPUP_NORMAL                        0x8009
#define HID_POPUP_BELOW_NORMAL                  0x800A
#define HID_POPUP_LOWEST                        0x800B
#define HID_POPUP_IDLE                          0x800C
#define HID_POPUP_CUSTOM_BUFFERSIZE             0x8019
#define HID_POPUP_OPTIONS                       0x8022
#define HID_SHOW_MINI_VIEW                      0x8023
#define HID_POPUP_CUSTOM_COPY                   0x8024
#define HID_POPUP_REPLACE_PATHS                 0x8025
#define HID_POPUP_MONITORING                    0x8026
#define HID_POPUP_SHUTAFTERFINISHED             0x8027
#define HID_POPUP_REGISTERDLL                   0x8029
#define HID_POPUP_UNREGISTERDLL                 0x802A
#define HID_POPUP_HELP                          0x802E
#define HID_POPUP_TEMP                          0x802F
  
// Prompts (IDP_*)  
  
// Resources (IDR_*)  
#define HIDR_MANIFEST                           0x20001
#define HIDR_MAINFRAME                          0x20080
#define HIDR_SYSTEMTYPE                         0x20081
#define HIDR_POPUP_MENU                         0x20082
#define HIDR_PRIORITY_MENU                      0x20087
#define HIDR_BUFFERSIZE_MENU                    0x20088
#define HIDR_PAUSE_LIST_MENU                    0x2008A
#define HIDR_ADVANCED_MENU                      0x200A0
#define HIDR_POPUP_TOOLBAR                      0x200AA
#define HIDR_THANKS_TEXT                        0x200D3
  
// Dialogs (IDD_*)  
#define HIDD_ABOUTBOX                           0x20064
#define HIDD_STATUS_DIALOG                      0x20083
#define HIDD_BUFFERSIZE_DIALOG                  0x20089
#define HIDD_OPTIONS_DIALOG                     0x20090
#define HIDD_MINIVIEW_DIALOG                    0x20091
#define HIDD_CUSTOM_COPY_DIALOG                 0x20095
#define HIDD_FOLDER_BROWSING_DIALOG             0x20096
#define HIDD_NEW_FOLDER_DIALOG                  0x20097
#define HIDD_NEW_QUICK_ACCESS_DIALOG            0x20098
#define HIDD_REPLACE_PATHS_DIALOG               0x200A1
#define HIDD_FEEDBACK_IGNOREWAITRETRY_DIALOG    0x200A2
#define HIDD_FEEDBACK_REPLACE_FILES_DIALOG      0x200A4
#define HIDD_FEEDBACK_SMALL_REPLACE_FILES_DIALOG	0x200A5
#define HIDD_FEEDBACK_DSTFILE_DIALOG            0x200A7
#define HIDD_FEEDBACK_NOTENOUGHPLACE_DIALOG     0x200AD
#define HIDD_SHUTDOWN_DIALOG                    0x200B6
#define HIDD_FILTER_DIALOG                      0x200C3
#define HIDD_SHORTCUTEDIT_DIALOG                0x200D0
#define HIDD_RECENTEDIT_DIALOG                  0x200D1
  
// Frame Controls (IDW_*)  
  
// Controls (IDC_*)  
#define IDH_ABOUTBOX                            0xD2
#define IDH_PROGRAM_STATIC                      0x3E8
#define IDH_ADDFILE_BUTTON                      0x3EA
#define IDH_STATUS_LIST                         0x3EB
#define IDH_REMOVEFILEFOLDER_BUTTON             0x3EC
#define IDH_ALL_PROGRESS                        0x3ED
#define IDH_DESTPATH_EDIT                       0x3EE
#define IDH_TASK_PROGRESS                       0x3EF
#define IDH_DESTBROWSE_BUTTON                   0x3F0
#define IDH_OPERATION_COMBO                     0x3F1
#define IDH_FILTERS_LIST                        0x3F2
#define IDH_ADDDIR_BUTTON                       0x3F3
#define IDH_BUFFERSIZES_LIST                    0x3F4
#define IDH_SET_BUFFERSIZE_BUTTON               0x3F5
#define IDH_FILTERS_CHECK                       0x3F6
#define IDH_IGNOREFOLDERS_CHECK                 0x3F7
#define IDH_SET_PRIORITY_BUTTON                 0x3F8
#define IDH_ONLYSTRUCTURE_CHECK                 0x3F9
#define IDH_PAUSE_BUTTON                        0x3FA
#define IDH_STANDARD_CHECK                      0x3FB
#define IDH_FORCEDIRECTORIES_CHECK              0x3FC
#define IDH_RESUME_BUTTON                       0x3FD
#define IDH_CANCEL_BUTTON                       0x3FE
#define IDH_ADVANCED_CHECK                      0x3FF
#define IDH_BUFFERSIZES_BUTTON                  0x400
#define IDH_ADDFILTER_BUTTON                    0x401
#define IDH_REMOVEFILTER_BUTTON                 0x402
#define IDH_SOURCE_STATIC                       0x403
#define IDH_DESTINATION_STATIC                  0x404
#define IDH_OPERATION_STATIC                    0x405
#define IDH_BUFFERSIZE_STATIC                   0x406
#define IDH_PRIORITY_STATIC                     0x407
#define IDH_ERRORS_STATIC                       0x408
#define IDH_PROGRESS_STATIC                     0x409
#define IDH_TRANSFER_STATIC                     0x40A
#define IDH_OVERALL_PROGRESS_STATIC             0x40B
#define IDH_OVERALL_TRANSFER_STATIC             0x40C
#define IDH_TIME_STATIC                         0x40D
#define IDH_ROLL_UNROLL_BUTTON                  0x40E
#define IDH_SIZE_EDIT                           0x40F
#define IDH_ASSOCIATEDFILES__STATIC             0x410
#define IDH_START_ALL_BUTTON                    0x411
#define IDH_RESTART_BUTTON                      0x412
#define IDH_DELETE_BUTTON                       0x413
#define IDH_PAUSE_ALL_BUTTON                    0x414
#define IDH_RESTART_ALL_BUTTON                  0x415
#define IDH_CANCEL_ALL_BUTTON                   0x416
#define IDH_REMOVE_FINISHED_BUTTON              0x417
#define IDH_PROPERTIES_LIST                     0x418
#define IDH_PROGRESS_LIST                       0x419
#define IDH_SOURCE_EDIT                         0x41A
#define IDH_DESTINATION_EDIT                    0x41B
#define IDH_DIRECTORY_TREE                      0x41D
#define IDH_QUICK_ACCESS_LIST                   0x41E
#define IDH_PATH_EDIT                           0x41F
#define IDH_HEADER_TEXT_STATIC                  0x420
#define IDH_FIND_PATH_BUTTON                    0x421
#define IDH_NEW_FOLDER_BUTTON                   0x422
#define IDH_PATH_STATIC                         0x423
#define IDH_ADD_BUTTON                          0x424
#define IDH_REMOVE_BUTTON                       0x425
#define IDH_TITLE_EDIT                          0x426
#define IDH_BROWSE_BUTTON                       0x428
#define IDH_FILES_LIST                          0x429
#define IDH_ADD_DIRECTORY_BUTTON                0x42A
#define IDH_MASK_EDIT                           0x42B
#define IDH_OPERATION_TYPE_COMBO                0x42C
#define IDH_ADD_FILES_BUTTON                    0x42D
#define IDH_BUFFERSIZE_EDIT                     0x42E
#define IDH_PRIORITY_COMBO                      0x42F
#define IDH_IGNORE_FOLDERS_CHECK                0x431
#define IDH_ONLY_CREATE_CHECK                   0x432
#define IDH_ADVANCED_BUTTON                     0x435
#define IDH_PATHS_LIST                          0x436
#define IDH_FILENAME_EDIT                       0x440
#define IDH_FILESIZE_EDIT                       0x441
#define IDH_DESTFILENAME_EDIT                   0x442
#define IDH_CREATETIME_EDIT                     0x443
#define IDH_MODIFY_TIME_EDIT                    0x444
#define IDH_DEST_FILENAME_EDIT                  0x445
#define IDH_DEST_FILESIZE_EDIT                  0x446
#define IDH_DEST_CREATETIME_EDIT                0x447
#define IDH_DEST_MODIFYTIME_EDIT                0x448
#define IDH_IGNORE_BUTTON                       0x449
#define IDH_IGNORE_ALL_BUTTON                   0x44A
#define IDH_WAIT_BUTTON                         0x44B
#define IDH_RETRY_BUTTON                        0x44C
#define IDH_COPY_REST_BUTTON                    0x44F
#define IDH_RECOPY_BUTTON                       0x450
#define IDH_COPY_REST_ALL_BUTTON                0x452
#define IDH_RECOPY_ALL_BUTTON                   0x453
#define IDH_MESSAGE_EDIT                        0x458
#define IDH_COUNT_EDIT                          0x45F
#define IDH_SHOW_LOG_BUTTON                     0x460
#define IDH_STICK_BUTTON                        0x462
#define IDH_FREESPACE_STATIC                    0x463
#define IDH_DISK_STATIC                         0x464
#define IDH_REQUIRED_STATIC                     0x467
#define IDH_AVAILABLE_STATIC                    0x468
#define IDH_TEST_BUTTON                         0x469
#define IDH_SOURCEFILENAME_EDIT                 0x46A
#define IDH_YESALL_BUTTON                       0x46B
#define IDH_NOALL_BUTTON                        0x46C
#define IDH_DEFAULTMULTIPLIER_COMBO             0x46D
#define IDH_DEFAULTSIZE_EDIT                    0x46E
#define IDH_ONEDISKSIZE_EDIT                    0x46F
#define IDH_CHANGEBUFFER_BUTTON                 0x471
#define IDH_ONEDISKMULTIPLIER_COMBO             0x472
#define IDH_TWODISKSSIZE_EDIT                   0x473
#define IDH_TWODISKSMULTIPLIER_COMBO            0x474
#define IDH_CDROMSIZE_EDIT                      0x475
#define IDH_CDROMMULTIPLIER_COMBO               0x476
#define IDH_LANSIZE_EDIT                        0x477
#define IDH_LANMULTIPLIER_COMBO                 0x478
#define IDH_ONLYDEFAULT_CHECK                   0x479
#define IDH_TIME_PROGRESS                       0x47A
#define IDH_ERRORS_EDIT                         0x47B
#define IDH_FILTER_COMBO                        0x47D
#define IDH_FILTER_CHECK                        0x47E
#define IDH_SIZE_CHECK                          0x47F
#define IDH_SIZE1_EDIT                          0x480
#define IDH_SIZE1MULTI_COMBO                    0x481
#define IDH_SIZETYPE1_COMBO                     0x482
#define IDH_SIZE1_SPIN                          0x483
#define IDH_SIZE2_EDIT                          0x484
#define IDH_SIZE2MULTI_COMBO                    0x485
#define IDH_SIZETYPE2_COMBO                     0x486
#define IDH_SIZE2_SPIN                          0x487
#define IDH_SIZE2_CHECK                         0x488
#define IDH_DATE_CHECK                          0x489
#define IDH_ATTRIBUTES_CHECK                    0x48A
#define IDH_ARCHIVE_CHECK                       0x48B
#define IDH_READONLY_CHECK                      0x48C
#define IDH_HIDDEN_CHECK                        0x48D
#define IDH_SYSTEM_CHECK                        0x48E
#define IDH_DATETYPE_COMBO                      0x48F
#define IDH_DATE1TYPE_COMBO                     0x490
#define IDH_DATE1_DATETIMEPICKER                0x491
#define IDH_TIME1_DATETIMEPICKER                0x492
#define IDH_DATE2_CHECK                         0x493
#define IDH_DATE2TYPE_COMBO                     0x494
#define IDH_DATE2_DATETIMEPICKER                0x495
#define IDH_TIME2_DATETIMEPICKER                0x496
#define IDH_DIRECTORY_CHECK                     0x497
#define IDH_FILTEREXCLUDE_COMBO                 0x498
#define IDH_EXCLUDEMASK_CHECK                   0x499
#define IDH_COUNT_SPIN                          0x49A
#define IDH_DESTPATH_COMBOBOXEX                 0x49B
#define IDH_SHORTCUT_LIST                       0x49C
#define IDH_NAME_EDIT                           0x49D
#define IDH_PATH_COMBOBOXEX                     0x49E
#define IDH_CHANGE_BUTTON                       0x4A1
#define IDH_RECENT_LIST                         0x4A6
#define IDH_IMPORT_BUTTON                       0x4A7
#define IDH_UP_BUTTON                           0x4A8
#define IDH_DOWN_BUTTON                         0x4A9
#define IDH_THANX_EDIT                          0x4AE
#define IDH_COPYRIGHT_STATIC                    0x4AF
#define IDH_FOLDER_TREE                         0x4B0
#define IDH_DISTRIBUTION_STATIC                 0x4B0
#define IDH_NEWFOLDER_BUTTON                    0x4B1
#define IDH_HOMEPAGE_STATIC                     0x4B1
#define IDH_TITLE_STATIC                        0x4B2
#define IDH_HOMEPAGELINK_STATIC                 0x4B2
#define IDH_LARGEICONS_BUTTON                   0x4B3
#define IDH_CONTACT_STATIC                      0x4B3
#define IDH_HOMEPAGELINK2_STATIC                0x4B3
#define IDH_SMALLICONS_BUTTON                   0x4B4
#define IDH_GENFORUM_STATIC                     0x4B4
#define IDH_LIST_BUTTON                         0x4B5
#define IDH_DEVFORUM_STATIC                     0x4B5
#define IDH_REPORT_BUTTON                       0x4B6
#define IDH_CONTACT1LINK_STATIC                 0x4B6
#define IDH_CONTACT2LINK_STATIC                 0x4B7
#define IDH_GENFORUMPAGELINK_STATIC             0x4B8
#define IDH_TOGGLE_BUTTON                       0x4B9
#define IDH_GENFORUMSUBSCRIBELINK_STATIC        0x4B9
#define IDH_ADDSHORTCUT_BUTTON                  0x4BA
#define IDH_GENFORUMUNSUBSCRIBELINK_STATIC      0x4BA
#define IDH_REMOVESHORTCUT_BUTTON               0x4BB
#define IDH_GENFORUMSENDLINK_STATIC             0x4BB
#define IDH_DEVFORUMPAGELINK_STATIC             0x4BC
#define IDH_DEVFORUMSUBSCRIBELINK_STATIC        0x4BD
#define IDH_DEVFORUMUNSUBSCRIBELINK_STATIC      0x4BE
#define IDH_DEVFORUMSENDLINK_STATIC             0x4BF
#define IDH_THANX_STATIC                        0x4C0
#define IDH_UPX_STATIC                          0x4C1
#define IDH_CONTACT3LINK_STATIC                 0x4C1
#define IDH_APPLY_BUTTON                        0x4C2
#define IDH_001_STATIC                          0x4C3
#define IDH_002_STATIC                          0x4C4
#define IDH_003_STATIC                          0x4C5
#define IDH_004_STATIC                          0x4C6
#define IDH_005_STATIC                          0x4C7
#define IDH_006_STATIC                          0x4C8
#define IDH_007_STATIC                          0x4C9
#define IDH_008_STATIC                          0x4CA
#define IDH_009_STATIC                          0x4CB
#define IDH_010_STATIC                          0x4CC
#define IDH_011_STATIC                          0x4CD
#define IDH_012_STATIC                          0x4CE
#define IDH_013_STATIC                          0x4CF
#define IDH_014_STATIC                          0x4D0
#define IDH_015_STATIC                          0x4D1
#define IDH_016_STATIC                          0x4D2
#define IDH_017_STATIC                          0x4D3
#define IDH_018_STATIC                          0x4D4
#define IDH_019_STATIC                          0x4D5
#define IDH_020_STATIC                          0x4D6
#define IDH_021_STATIC                          0x4D7
#define IDH_022_STATIC                          0x4D8
#define IDH_023_STATIC                          0x4D9
#define IDH_024_STATIC                          0x4DA
#define IDH_025_STATIC                          0x4DB
#define IDH_026_STATIC                          0x4DC
#define IDH_027_STATIC                          0x4DD
#define IDH_028_STATIC                          0x4DE
#define IDH_029_STATIC                          0x4DF
#define IDH_030_STATIC                          0x4E0
#define IDH_BAR1_STATIC                         0x4E1
#define IDH_BAR2_STATIC                         0x4E2
#define IDH_BAR3_STATIC                         0x4E3
#define IDH_BAR4_STATIC                         0x4E4
#define IDH_BAR5_STATIC                         0x4E5
#define IDH_HEADER_STATIC                       0x4E6
#define IDH_HOSTLINK_STATIC                     0x4E7
#define IDH_HELP_BUTTON                         0x4E9
#define IDH_PROGRAM_STATICEX                    0x4EF
#define IDH_FULLVERSION_STATICEX                0x4F0
#define IDH_HOMEPAGE_STATICEX                   0x4F1
#define IDH_CONTACT_STATICEX                    0x4F2
#define IDH_LICENSE_STATICEX                    0x4F3
#define IDH_CONTACTAUTHOR_STATICEX              0x4F4
#define IDH_CONTACTSUPPORT_STATICEX             0x4F5
